App/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('administrador/',views.admin,name="admin"),
    path('gefe/',views.gefe,name="gefe"),

    path('administrador/articulos/',views.mostrar_articulos_admin,name="articulos_admin"),
    path('articulos/vender/',views.vender_articulos,name="vender"),

    path('articulos/',views.mostrar_articulos_empleado,name="articulos"),
    path('administrador/articulos/modificar/articulo/<int:art>',views.modificar_articulos,name="modificar"),
    path('administrador/articulos/eliminar/',views.eliminar_articulos,name="eliminar"),
    path('administrador/articulos/agregar/',views.agregar_articulos,name="agregar"),
    path('administrador/articulos/rubros/',views.rubros,name="rubros"),
    path('administrador/articulos/modificar/rubro/<int:rub>',views.modificar_rubro,name="modificar_rubro"),


    path('gefe/agregar_empleado/',views.agregar_empleado,name="agregar_empleado"),
    path('gefe/modificar_empleado/',views.modificar_empleado,name="modificar_empleado"),
    path('gefe/empleados/',views.empleados,name="empleados"),
    path('gefe/ventas/',views.ventas,name="ventas"),

    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Kiosco/urls.py
from django.contrib import admin
from django.urls import path, include
import App

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls'),name="home"),
]

App/models.py
from django.db import models
#from django import forms

# Create your models here.

#funciones
#def subir_archivo(instance, filename):
#	return 'files/%s'% instance.nom_foro +'/%s'% filename

#Campos


#Articulos
class Rubros(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion


class Articulos(models.Model):
    nombre_art = models.CharField(max_length=30)
    precio = models.IntegerField()
    rubro = models.ForeignKey(Rubros, on_delete=models.SET_NULL,null=True)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre_art



#Persona

class Domicilio(models.Model):
    localizacion = models.CharField(max_length=50)

    def __str__(self):
        return self.localizacion


class Contacto(models.Model):
    telefono = models.IntegerField(null = True)
    correo = models.CharField(max_length=50, null = True)

    def __str__(self):
        return self.correo


class Datos_personales(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    fecha_nac = models.DateField()
    domicilio = models.ForeignKey(Domicilio, on_delete=models.CASCADE)
    contacto = models.ForeignKey(Contacto, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str( str(self.nombre) + " " + str(self.apellido))
        

class Tipo_persona(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion


class Legajo_empleado(models.Model):
    antiguedad = models.DateField()
    salario = models.IntegerField()

    def __str__(self):
        return str( str(self.antiguedad) + "($" + str(self.salario) + ")" )


class Personas(models.Model):
    datos_personales = models.ForeignKey(Datos_personales, on_delete=models.CASCADE)
    tipo_persona = models.ForeignKey(Tipo_persona, on_delete=models.CASCADE)
    legajo_empleado = models.ForeignKey(Legajo_empleado, on_delete=models.CASCADE)

    def __str__(self):
        return str( str(self.datos_personales.nombre) + " " + str(self.datos_personales.apellido))




#Ventas y factura

class Det_factura(models.Model):
    precio = models.IntegerField()
    fecha_compra = models.DateField()
    cant_compra = models.IntegerField()
    tipo_persona = models.ForeignKey(Tipo_persona, on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return str(self.fecha_compra)


class Facturas(models.Model):
    articulo = models.ForeignKey(Articulos, on_delete=models.SET_NULL,null=True)
    descripcion = models.CharField(max_length=50)
    detalle = models.ForeignKey(Det_factura, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.descripcion


class Det_venta(models.Model):
    articulo = models.ForeignKey(Articulos, on_delete=models.SET_NULL,null=True)
    fecha_venta = models.DateField()
    precio = models.IntegerField()
    cant_venta = models.IntegerField()

    def __str__(self):
        return str(self.fecha_venta)



class Ventas(models.Model):
    factura = models.ForeignKey(Facturas, on_delete=models.CASCADE)
    det_venta = models.ForeignKey(Det_venta, on_delete=models.CASCADE)
    persona = models.ForeignKey(Personas, on_delete=models.CASCADE)
    
    def __str__(self):
        return str( str(self.persona) + "(" + str(self.det_venta.fecha_venta) + ")" )

#class Persona(models.Model):
    #datos_personales = ForeignKey(Rubros, on_delete=models.CASCADE)

App/templates/App/admin.html
{% extends 'App/template.html' %}
{% load static %}

{% block contenido %}

<a href="{% url 'articulos_admin' %}"><button class="btn btn-outline-primary btn-lg">Articulos</button></a>
<a href="{% url 'agregar' %}"><button class="btn btn-outline-primary btn-lg">Agregar Articulo</button></a>
<a href="{% url 'rubros' %}"><button class="btn btn-outline-primary btn-lg">Rubros</button></a>

<div class="border border-primary container"><br>
{% block admin %}
    

{% endblock %}
</div>

{% endblock %}

App/templates/App/agregar_articulo.html
{% extends 'App/admin.html' %}
{% load static %}



{% block admin %}
    <div class="container">

    <label><h4>{{ Estado }}</h4></label>

    <form action="{% url 'agregar'%}" method="POST">
        {% csrf_token %}

        <p>
            <label>Articulo:</label>
            {{ Formulario.nombre_art }}
        </p>
        
        <p>
            <label>Precio:$</label>
            {{ Formulario.precio }}
        </p>
        
        <p>
            <label>Rubro:</label>

            <input type="radio" id="list" name="rub" value="list" checked>
            {{ Formulario.rubro }}
            <input type="radio" id="text" name="rub" value="text">
            <input type="text" id="textrub" placeholder="Nuevo rubro" disabled name="agregar_rubro">
        </p>
        
        <p>
            <label>Stock:</label>
            {{ Formulario.stock }}
        </p>
        

        <button class="btn btn-outline-info">Agregar</button>
    </form><br>

    </div>

    <script>
        var enlista = false

        document.addEventListener("click", function(){

            if ($("#list").is(":checked") ){
                $("#textrub").prop('disabled', true);
                $("#id_rubro").prop('disabled', false);
            }else{
                $("#textrub").prop('disabled', false);
                $("#id_rubro").prop('disabled', true);
            }
        });


    </script>


{% endblock %}

App/templates/App/agregar_empleado.html
{% extends 'App/gefe.html' %}
{% load static %}

{% block gefe %}
    <div class="container">

        <label><h4>{{ Estado }}</h4></label>

        <form action="{% url 'agregar_empleado' %}" method="POST">
            {% csrf_token %}

            <label>Nombre:</label>
            <input type="text" name="Nombre" required>

            <label>Apellido:</label>
            <input type="text" name="Apellido" required><br><br>

            <label>Fecha de nacimiento:</label>
            <input type="date" name="Fecha_Nac" required><br><br>

            <label>Fecha de ingreso(Antigüedad):</label>
            <input type="date" name="Fecha_Ing" required><br><br>












            <label>Domicilio:</label>

            <input type="radio" id="list" name="dom" value="list" checked>

            <select id="list_domicilio" name="Domicilio" required>
                <option value>------</option>
                {% for i in Domicilios %}
                    {% if i.localizacion == Persona.datos_personales.domicilio.localizacion %}
                        <option value="{{ i.id }}" selected >{{ i.localizacion }}</option>
                    {% else %}
                        <option value="{{ i.id }}" >{{ i.localizacion }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <input type="radio" id="text" name="dom" value="text">
            <input type="text" id="text_domicilio" placeholder="Nuevo domicilio" disabled name="agregar_domicilio" required><br><br>









            <label>Numero de Telefono(Opcional):</label>
            <input type="number" name="Telefono"><br><br>

            <label>Correo electronico(Opcional):</label>
            <input type="text" name="Correo"><br><br>

            <label>Tipo de persona:</label>
            <select name="Tipo_Persona" required>
                <option value>------</option>
                {% for i in TiposPersona %}
                    <option value="{{ i.id }}">{{ i.descripcion }}</option>
                {% endfor %}
            </select><br><br>

            <label>Salario:$</label>
            <input type="number" name="Salario" required><br><br>
            
            <button class="btn btn-outline-info">Guardar</button>
        </form><br><br>

        
    </div>





    <script>
        var enlista = false
    
        document.addEventListener("click", function(){
    
            if ($("#list").is(":checked") ){
                $("#text_domicilio").prop('disabled', true);
                $("#list_domicilio").prop('disabled', false);
            }else{
                $("#text_domicilio").prop('disabled', false);
                $("#list_domicilio").prop('disabled', true);
            }
        });
    </script>


{% endblock %}

App/templates/App/articulos.html
{% extends 'App/template.html' %}
{% load static %}

{% block contenido %}

<table class="table table-bordered">
    <tr>
        <td align="center"><b>Articulo</b></td>
        <td align="center"><b>Precio</b></td>
        <td align="center"><b>Rubro</b></td>
        <td align="center"><b>Stock</b></td>
        <td></td>
    </tr>
    
    {% for i in Articulos %}
        <tr>
            <td align="center"> {{ i.nombre_art }} </td>
            <td align="center"> {{ i.precio }} </td>
            <td align="center"> {{ i.rubro.descripcion }} </td>
            <td align="center"> {{ i.stock }} </td>
            {% if i.stock > 0 %}
                <td>
                    <a href="{% url 'vender' %}?id={{ i.id }}"><button class="btn btn-outline-success btn-block"><i class="icon-min peso"></i>Vender</button></a>
                </td>
            {% endif %}
        </tr>
    {% endfor %}
</table>

{% endblock %}

App/templates/App/articulos_admin.html
{% extends 'App/admin.html' %}
{% load static %}

{% block admin %}

<table class="table table-bordered" >
    <tr>
        <td align="center"><b>Articulo</b></td>
        <td align="center"><b>Precio</b></td>
        <td align="center"><b>Rubro</b></td>
        <td align="center"><b>Stock</b></td>
        <td align="center" colspan=2><b>Acciones<b></td>
    </tr>
    
    {% for i in Articulos %}
        <tr>
            <td align="center"> {{ i.nombre_art }} </td>
            <td align="center"> {{ i.precio }} </td>
            <td align="center"> {{ i.rubro.descripcion }} </td>
            <td align="center"> {{ i.stock }} </td>
            <td> <a href="{% url 'modificar' art=i.id %}"><button class="btn btn-outline-primary btn-block">Modificar</button></a> </td>
            <td>  <button onclick="Preguntar( '{{ i.id }}' )" class="btn btn-outline-danger btn-block" ><i class="icon-min basura"></i>Eliminar</button> </td>
        </tr>
    {% endfor %}
</table>


<script>
    function Preguntar(variable){
        variable = parseInt(variable)
        confirmacion = window.confirm("Esta seguro de eliminar este articulo?")
        if(confirmacion == true){
            window.location.href = "{% url 'eliminar' %}?id=" + variable;
        }
    }

    ///window.location.href
</script>

{% endblock %}

App/templates/App/empleados.html
{% extends 'App/gefe.html' %}
{% load static %}

{% block gefe %}

    <label><h4>{{ Estado }}</h4></label>

<table class="table table-bordered" >
    <tr>
        <td align="center"><b>Nombre</b></td>
        <td align="center"><b>Tipo</b></td>
        <td align="center"><b>Domicilio</b></td>
        <td align="center"><b>Antiguedad</b></td>
        <td align="center"><b>Salario</b></td>
        <td align="center"><b>Fecha Nacimiento</b></td>
        <td align="center"><b>Contacto</b></td>
        <td align="center" colspan="2"><b>Acciones</b></td>
    </tr>
    
    {% for i in Empleados %}
        <tr>
            <td align="center"> {{ i.datos_personales.nombre }} {{ i.datos_personales.apellido }} </td>
            <td align="center"> {{ i.tipo_persona.descripcion }} </td>
            <td align="center"> {{ i.datos_personales.domicilio.localizacion }} </td>
            <td align="center"> {{ i.legajo_empleado.antiguedad }} </td>
            <td align="center"> ${{ i.legajo_empleado.salario }} </td>
            <td align="center"> {{ i.datos_personales.fecha_nac }} </td>
            <td> 
                <label>Telefono: </label>{{ i.datos_personales.contacto.telefono }}<br>
                <label>Correo: </label>{{ i.datos_personales.contacto.correo }} 
            </td>

            <td> <a href="{% url 'modificar_empleado' %}?idpersona={{ i.id }}"> <button class="btn btn-outline-primary btn-block">Modificar</button></a></td>
            <td><button onclick="Preguntar( '{{ i.id }}' )" class="btn btn-outline-danger btn-block">Eliminar</button></td>

        </tr>
    {% endfor %}

</table>


<script>
    function Preguntar(variable){
    variable = parseInt(variable)
    confirmacion = window.confirm("Esta seguro de eliminar al empleado?")
        if(confirmacion == true){
            window.location.href = "{% url 'empleados' %}?id=" + variable;
        }
    }
</script>


{% endblock %}

App/templates/App/gefe.html
{% extends 'App/template.html' %}
{% load static %}

{% block contenido %}


<a href="{% url 'ventas' %}"><button class="btn btn-outline-primary btn-lg">Ventas</button></a>
<a href="{% url 'empleados' %}"><button class="btn btn-outline-primary btn-lg">Empleados</button></a>
<a href="{% url 'agregar_empleado' %}"><button class="btn btn-outline-primary btn-lg">Agregar empleado</button></a>

<div class="border border-primary container"><br>
{% block gefe %}
    

{% endblock %}
</div>

{% endblock %}

App/templates/App/modificar_articulo.html
{% extends 'App/admin.html' %}
{% load static %}



{% block admin %}
    <a href="{% url 'articulos_admin' %}"><button class="btn btn-outline-primary">Volver</button></a><br><br>

    <label><h4>{{ Estado }}</h4></label><br>

    <form action="{% url 'modificar' art=Id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="idart" value="{{ Id }}">
        {{ Formulario.as_p }}
        <button class="btn btn-outline-info">Modificar</button>
    </form>
    

{% endblock %}

App/templates/App/modificar_empleado.html
{% extends 'App/gefe.html' %}
{% load static %}

{% block gefe %}

<a href="{% url 'empleados' %}"><button class="btn btn-outline-info">Volver</button></a><br><br>


<label><h4>{{ Estado }}</h4></label><br>

<form action="{% url 'modificar_empleado' %}" method="POST">
    {% csrf_token %}

    <input type="hidden" value="{{ Persona.id }}" name="id">

    <label>Nombre:</label>
    <input type="text" value="{{ Persona.datos_personales.nombre }}" name="Nombre" required>

    <label>Apellido:</label>
    <input type="text" value="{{ Persona.datos_personales.apellido }}" name="Apellido" required><br><br>

    <label>Fecha de nacimiento:</label>
    <input type="date" name="Fecha_Nac" value="{{ Persona.datos_personales.fecha_nac|date:'Y-m-d' }}" required><br><br>

    <label>Fecha de ingreso(Antigüedad):</label>
    <input type="date" name="Fecha_Ing" value="{{ Persona.legajo_empleado.antiguedad|date:'Y-m-d' }}" required><br><br>




    <label>Domicilio:</label>

    <input type="radio" id="list" name="dom" value="list" checked>

    <select id="list_domicilio" name="Domicilio" required>
        <option value>------</option>
        {% for i in Domicilios %}
            {% if i.localizacion == Persona.datos_personales.domicilio.localizacion %}
                <option value="{{ i.id }}" selected >{{ i.localizacion }}</option>
            {% else %}
                <option value="{{ i.id }}" >{{ i.localizacion }}</option>
            {% endif %}
        {% endfor %}
    </select>

    <input type="radio" id="text" name="dom" value="text">
    <input type="text" id="text_domicilio" placeholder="Nuevo domicilio" disabled name="agregar_domicilio" required><br><br>






    <label>Numero de Telefono(Opcional):</label>
    <input type="number" value="{{ Persona.datos_personales.contacto.telefono }}" name="Telefono"><br><br>

    <label>Correo electronico(Opcional):</label>
    <input type="text" value="{{ Persona.datos_personales.contacto.correo }}" name="Correo"><br><br>

    <label>Tipo de persona:</label>
    <select name="Tipo_Persona" required>
        <option value>------</option>
        {% for i in TiposPersonas %}
            {% if i.descripcion == Persona.tipo_persona.descripcion %}
                <option selected value="{{ i.id }}">{{ i.descripcion }}</option>
            {% else %}
                <option value="{{ i.id }}">{{ i.descripcion }}</option>
            {% endif %}
        {% endfor %}
    </select><br><br>

    <label>Salario:$</label>
    <input type="number" value="{{ Persona.legajo_empleado.salario }}" name="Salario" required><br><br>
    
    <button class="btn btn-outline-info">Guardar</button>
</form><br><br>



<script>
    var enlista = false

    document.addEventListener("click", function(){

        if ($("#list").is(":checked") ){
            $("#text_domicilio").prop('disabled', true);
            $("#list_domicilio").prop('disabled', false);
        }else{
            $("#text_domicilio").prop('disabled', false);
            $("#list_domicilio").prop('disabled', true);
        }
    });
</script>

{% endblock %}

App/templates/App/modificar_rubro.html
{% extends 'App/admin.html' %}
{% load static %}

{% block admin %}
    <a href="{% url 'rubros' %}"><button class="btn btn-outline-primary">Volver</button></a><br><br>
    <p>
        <form action="{% url 'modificar_rubro' Rubro.id %}" method="POST">
            {% csrf_token %}
            <label>Rubro:</label>
            <input type="hidden" value="{{ Rubro.id }}" name="id">
            <input type="text" value="{{ Rubro.descripcion }}" name="new">
            <button class="btn btn-outline-info">Modificar</button>
            <p>
                <label><h3>{{ Estado }}</h3></label>
            </p>
            
        </form>
    </p>

{% endblock %}

App/templates/App/rubros.html
{% extends 'App/admin.html' %}
{% load static %}

{% block admin %}
    <div class="container">
        <p>
            <form action="{% url 'rubros' %}" method="POST">
                {% csrf_token %}
                <input type="text" placeholder="Agregar nuevo rubro" name="newrubro">
                <button class="btn btn-outline-info">Agregar</button>
                <label>{{ Estado }}</label>
            </form>
        </p>
    </div>

    <table class="table table-bordered" >
    <tr>
        <td><b>Rubros</b></td>
        <td align="center" colspan=2><b>Acciones</b></td>
    </tr>
    
    {% for i in Rubros %}
        <tr>
            <td align="center"> {{ i.descripcion }} </td>
            <td> <a href="{% url 'modificar_rubro' i.id %}"><button class="btn btn-outline-primary btn-block">Modificar</button></a> </td>
            <td><button onclick="Preguntar( '{{ i.id }}' )" class="btn btn-outline-danger btn-block" ><i class="icon-min basura"></i>Eliminar</button></td>
        </tr>
    {% endfor %}
    </table>

    <script>
        function Preguntar(variable){
        variable = parseInt(variable)
        confirmacion = window.confirm("Esta seguro de eliminar este rubro?")
            if(confirmacion == true){
                window.location.href = "{% url 'rubros' %}?idrubro=" + variable;
            }
        }
    </script>
{% endblock %}

App/templates/App/template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery/dist/jquery.min.js' %}"></script>
</head>
<style>
    html *{
        font-family: Comic-Sans;
    }

    html {
        background-color: #007bff;
    }

    body {
        background-color: #007bff;
    }

    .centro{
        width: 90%;
        margin-left: 8%;
        margin-top: 5%;
        border-radius: 20px;
    }
    .centroplus{
        padding: 50px;
    }

    .icon{
        background-size: cover;
        display:inline-block;
        height: 32px;
        width: 32px;
    }

    .icon-min{
        background-size: cover;
        display:inline-block;
        height: 13px;
        width: 13px;
    }

    .jefe{
        background-image : url("{% static 'svg/Jefe.svg' %}"); 
    }

    .admin{
        background-image : url("{% static 'svg/Admin.svg' %}");
    }

    .empleado{
        background-image : url("{% static 'svg/Empleado.svg' %}");
    }

    .peso{
        background-image : url("{% static 'svg/peso.svg' %}");
    }

    .basura{
        background-image : url("{% static 'svg/basura.svg' %}");
    }
</style>
<body>
        <div class="centro container bg-white">
            <div class="container centroplus">
            <a href="{% url 'gefe' %}"><button class="btn btn-outline-success btn-lg"><i class="icon jefe"></i> Modo Jefe</button></a>
            <a href="{% url 'admin' %}"><button class="btn btn-outline-success btn-lg"><i class="icon admin"></i>Modo Administrador</button></a>
            <a href="{% url 'articulos' %}"><button class="btn btn-outline-success btn-lg"><i class="icon empleado"></i>Modo Empleado</button></a><br><br>

            
            {% block contenido %}
            {% endblock %}
            </div>
        </div>

</body>
</html>

App/templates/App/vender.html
{% extends 'App/template.html' %}
{% load static %}

{% block contenido %}


    <a href="{% url 'articulos' %}"><button class="btn btn-outline-primary">Volver</button></a><br><br>

    <form action="{% url 'vender' %}" method="POST">
        {% csrf_token %}


        <label>Vendedor:</label>
        <select required name="Vendedor">
            <option value>-----</option>
            {% for i in Personas %}
                <option value="{{ i.id }}">{{ i.datos_personales.nombre }} {{ i.datos_personales.apellido }}</option>
            {% endfor %}
        </select><br><br>


        <label>Articulo:{{ Articulo.nombre_art }}</label><br>
        <input type="hidden" value="{{ Articulo.id }}" name="Articulo" >


        <label>Precio unidad: ${{ Articulo.precio }}</label><br><br>


        <label>Cantidad:</label> <input type="number" id="cantidad" min=1 max="{{ Articulo.stock }}" name="Cantidad" value="{{ Cantidad }}"><br>


        <label>Precio total:$</label>
        <label id="precio_total">{{ Total }}</label><br><br>
        <input type="hidden" id="total" name="Total" value="{{ Total }}">
        

        <label>Fecha:</label>
        <input type="date" name="Fecha" required value="{{ Fecha|date:'Y-m-d' }}"><br><br>


        <label>Descripcion:</label><br>
        <textarea name="Descripcion" cols="30" rows="3" required></textarea><br><br>

        
        <button class="btn btn-outline-success"><i class="icon-min peso"></i>Realizar venta</button>

    </form>






<script>
    $("#cantidad").change(function(){

        cantidad = $("#cantidad").val()

        if (cantidad <= 0){
            cantidad = 1;
            $("#cantidad").val(cantidad);
        }

        if(cantidad <= parseInt("{{ Articulo.stock }}")){
            total = cantidad * parseInt("{{ Articulo.precio }}");
            $("#precio_total").html(total);
            $("#total").val(total);
        }else{
            window.alert("La cantidad supera el stock");
            $("#cantidad").val(parseInt("{{ Articulo.stock }}"));
        }
    
    })
</script>

{% endblock %}

App/templates/App/ventas.html
{% extends 'App/gefe.html' %}
{% load static %}

{% block gefe %}


<table class="table table-bordered">
    <tr>
        <td align="center"><b>Fecha</b></td>
        <td align="center"><b>Vendedor</b></td>
        <td align="center"><b>Articulo</b></td>
        <td align="center"><b>Rubro</b></td>
        <td align="center"><b>Cantidad</b></td>
        <td align="center"><b>Total</b></td>
    </tr>
    
    {% for i in Ventas %}
        <tr>
            <td align="center"> {{ i.det_venta.fecha_venta }} </td>
            <td align="center"> {{ i.persona.datos_personales.nombre }} {{ i.persona.datos_personales.apellido }} </td>
            <td align="center"> {{ i.det_venta.articulo.nombre_art }} </td>
            <td align="center"> {{ i.det_venta.articulo.rubro.descripcion }} </td>
            <td align="center"> {{ i.det_venta.cant_venta }} </td>
            <td align="center"> ${{ i.det_venta.precio }} </td>
        </tr>
    {% endfor %}
</table>

{% endblock %}